var SpawnItem = require("./spawnItem.js");
	
module.exports = [
    /* R */
    new SpawnItem("Swelter Taurus","http://unisonleague.wikia.com/wiki/Swelter_Taurus_(Gear)", 1.0),
    new SpawnItem("Swelter Kong","http://unisonleague.wikia.com/wiki/Swelter_Kong_(Gear)", 1.0),
    new SpawnItem("Kin-ki","http://unisonleague.wikia.com/wiki/Kin-ki_(Gear)", 1.0),
    new SpawnItem("Croc Man","http://unisonleague.wikia.com/wiki/Croc_Man_(Gear)", 1.0),
    new SpawnItem("Mermaid","http://unisonleague.wikia.com/wiki/Mermaid_(Gear)", 1.0),
    new SpawnItem("Sea Serpent","http://unisonleague.wikia.com/wiki/Sea_Serpent_(Gear)", 1.0),
    new SpawnItem("Inky","http://unisonleague.wikia.com/wiki/Inky_(Gear)", 1.0),
    new SpawnItem("Kotaro the Stray Cat","http://unisonleague.wikia.com/wiki/Kotaro_the_Stray_Cat_(Gear)", 1.0),
    new SpawnItem("Crow Tengu","http://unisonleague.wikia.com/wiki/Crow_Tengu_(Gear)", 1.0),
    new SpawnItem("Kaava","http://unisonleague.wikia.com/wiki/Kaava_(Gear)", 1.0),
    new SpawnItem("Unicorn","http://unisonleague.wikia.com/wiki/Unicorn_(Gear)", 1.0),
    new SpawnItem("Exia Knight","http://unisonleague.wikia.com/wiki/Exia_Knight_(Gear)", 1.0),
    new SpawnItem("Val Leo","http://unisonleague.wikia.com/wiki/Val_Leo_(Gear)", 1.0),
    new SpawnItem("Banshee","http://unisonleague.wikia.com/wiki/Banshee_(Gear)", 1.0),
    new SpawnItem("Wyvern","http://unisonleague.wikia.com/wiki/Wyvern_(Gear)", 1.0),
    new SpawnItem("Medusa","http://unisonleague.wikia.com/wiki/Medusa_(Gear)", 1.0),
    new SpawnItem("Dullahan","http://unisonleague.wikia.com/wiki/Dullahan_(Gear)", 1.0),
    new SpawnItem("Cyclops","http://unisonleague.wikia.com/wiki/Cyclops_(Gear)", 1.0),
    new SpawnItem("Petrasaur","http://unisonleague.wikia.com/wiki/Petrasaur_(Gear)", 1.0),
    new SpawnItem("Golem","http://unisonleague.wikia.com/wiki/Golem_(Gear)", 1.0),
    /* SR */
    new SpawnItem("Firedrake Ignis","http://unisonleague.wikia.com/wiki/Firedrake_Ignis_(Gear)", 0.5),
    new SpawnItem("Ninetail Fox","http://unisonleague.wikia.com/wiki/Ninetail_Fox_(Gear)", 0.5),
    new SpawnItem("Leviathan","http://unisonleague.wikia.com/wiki/Leviathan_(Gear)", 0.5),
    new SpawnItem("Fenrir","http://unisonleague.wikia.com/wiki/Fenrir_(Gear)", 0.5),
    new SpawnItem("Hraesvelgr","http://unisonleague.wikia.com/wiki/Hraesvelgr_(Gear)", 0.5),
    new SpawnItem("Cuchulainn","http://unisonleague.wikia.com/wiki/Cuchulainn_(Gear)", 0.5),
    new SpawnItem("Etherful Golem","http://unisonleague.wikia.com/wiki/Etherful_Golem_(Gear)", 0.5),
    new SpawnItem("Physoth, Sacred Beast","http://unisonleague.wikia.com/wiki/Physoth,_Sacred_Beast_(Gear)", 0.5),
    new SpawnItem("Diablos","http://unisonleague.wikia.com/wiki/Diablos_(Gear)", 0.5),
    new SpawnItem("Metus, Evil Drake","http://unisonleague.wikia.com/wiki/Metus,_Evil_Drake_(Gear)", 0.5),
    /* SSR */
    new SpawnItem("Behemoth","http://unisonleague.wikia.com/wiki/Behemoth_(Gear)", 0.20),
    new SpawnItem("Valkyrie Falarn","http://unisonleague.wikia.com/wiki/Valkyrie_Falarn_(Gear)", 0.10),
    new SpawnItem("Kagutsuchi","http://unisonleague.wikia.com/wiki/Kagutsuchi_(Gear)", 0.15),
    new SpawnItem("Shinatobe, Beach Queen","http://unisonleague.wikia.com/wiki/Shinatobe,_Beach_Queen_(Gear)", 0.10),
    new SpawnItem("Joan of Arc","http://unisonleague.wikia.com/wiki/Joan_of_Arc_(Gear)", 0.15),
    new SpawnItem("Nobunaga","http://unisonleague.wikia.com/wiki/Nobunaga_(Gear)", 0.15),
    new SpawnItem("Apollo the Surfer","http://unisonleague.wikia.com/wiki/Apollo_the_Surfer_(Gear)", 0.1),
    new SpawnItem("Poseidon","http://unisonleague.wikia.com/wiki/Poseidon_(Gear)", 0.15),
    new SpawnItem("Valkyrie Raakyie","http://unisonleague.wikia.com/wiki/Valkyrie_Raakyie_(Gear)", 0.1),
    new SpawnItem("Siren","http://unisonleague.wikia.com/wiki/Siren_(Gear)", 0.15),
    new SpawnItem("Santa Flora","http://unisonleague.wikia.com/wiki/Santa_Flora_(Gear)", 0.1),
    new SpawnItem("Andromeda","http://unisonleague.wikia.com/wiki/Andromeda_(Gear)", 0.15),
    new SpawnItem("Ushiwakamaru","http://unisonleague.wikia.com/wiki/Ushiwakamaru_(Gear)", 0.15),
    new SpawnItem("Snow White","http://unisonleague.wikia.com/wiki/Snow_White_(Gear)", 0.1),
    new SpawnItem("Quetzalcoatl","http://unisonleague.wikia.com/wiki/Quetzalcoatl_(Gear)", 0.2),
    new SpawnItem("Shinatobe, Wind Caller","http://unisonleague.wikia.com/wiki/Shinatobe,_Wind_Caller_(Gear)", 0.15),
    new SpawnItem("Valkyrie Veere","http://unisonleague.wikia.com/wiki/Valkyrie_Veere_(Gear)", 0.1),
    new SpawnItem("Emilia, Dreamy Magic","http://unisonleague.wikia.com/wiki/Emilia,_Dreamy_Magic_(Gear)", 0.1),
    new SpawnItem("Gaia","http://unisonleague.wikia.com/wiki/Gaia_(Gear)", 0.1),
    new SpawnItem("Kirin","http://unisonleague.wikia.com/wiki/Kirin,_the_Wind_Beast_(Gear)", 0.15),
    new SpawnItem("Holiday Hel","http://unisonleague.wikia.com/wiki/Holiday_Hel_(Gear)", 0.1),
    new SpawnItem("Valkyrie","http://unisonleague.wikia.com/wiki/Valkyrie_(Gear)", 0.15),
    new SpawnItem("Indra, Storm God","http://unisonleague.wikia.com/wiki/Indra,_Storm_God_(Gear)", 0.15),
    new SpawnItem("Alice (French Maid)","http://unisonleague.wikia.com/wiki/Alice_(French_Maid)_(Gear)", 0.1),
    new SpawnItem("Nezha","http://unisonleague.wikia.com/wiki/Nezha_(Gear)", 0.15),
    new SpawnItem("Arthur, the Banneret","http://unisonleague.wikia.com/wiki/Arthur,_the_Banneret_(Gear)", 0.15),
    new SpawnItem("Athena","http://unisonleague.wikia.com/wiki/Athena_(Gear)", 0.1),
    new SpawnItem("Nyx the Songstress","http://unisonleague.wikia.com/wiki/Nyx_the_Songstress_(Gear)", 0.1),
    new SpawnItem("Lilith","http://unisonleague.wikia.com/wiki/Lilith_(Gear)", 0.2),
    new SpawnItem("Valkyrie Nikyt","http://unisonleague.wikia.com/wiki/Valkyrie_Nikyt_(Gear)", 0.1),
    new SpawnItem("Aizen","http://unisonleague.wikia.com/wiki/Aizen_(Gear)", 0.15),
    new SpawnItem("Anubis the Protector","http://unisonleague.wikia.com/wiki/Anubis_the_Protector_(Gear)", 0.15),
    new SpawnItem("Hel","http://unisonleague.wikia.com/wiki/Hel_(Gear)", 0.15),
    new SpawnItem("Merlyn","http://unisonleague.wikia.com/wiki/Merlyn_(Gear)", 0.1),
    new SpawnItem("HS Student Joan", "http://unisonleague.wikia.com/wiki/HS_Student_Joan_(Gear)", 0.1),
    new SpawnItem("Santa Lilith","http://unisonleague.wikia.com/wiki/Santa_Lilith_(Gear)", 0.1),
    new SpawnItem("Emilia, Tyro Witch","http://unisonleague.wikia.com/wiki/Emilia,_Tyro_Witch_(Gear)", 0.1),
    new SpawnItem("Skotos Athena", "http://unisonleague.wikia.com/wiki/Skotos_Athena_(Gear)", 0.1),
    new SpawnItem("Dragoon Cuchulainn","http://unisonleague.wikia.com/wiki/Dragoon_Cuchulainn_(Gear)", 0.1),
    new SpawnItem("Red Riding Hood","http://unisonleague.wikia.com/wiki/Red_Riding_Hood_(Gear)", 0.1),
    new SpawnItem("Melodic Fiine","http://unisonleague.wikia.com/wiki/Melodic_Fiine_(Gear)", 0.1),
    new SpawnItem("Sakuya, Sea Child","http://unisonleague.wikia.com/wiki/Sakuya,_Sea_Child_(Gear)", 0.1),
];
